package repository

import (
	"context"
	"database/sql"
	"myslotmate-backend/internal/models"

	"github.com/google/uuid"
)

// UserRepository defines the interface for user data access (Abstract Factory / Repository Pattern)
// This interface allows swapping implementations (e.g., PostgreSQL, Mock for testing)
type UserRepository interface {
	Create(ctx context.Context, user *models.User) error
	GetByEmail(ctx context.Context, email string) (*models.User, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.User, error)
	ExistsByEmail(ctx context.Context, email string) (bool, error)
	SetVerified(ctx context.Context, id uuid.UUID) error
}

// postgresUserRepository is the concrete implementation
type postgresUserRepository struct {
	db *sql.DB
}

// NewUserRepository Factory for creating a UserRepository
func NewUserRepository(db *sql.DB) UserRepository {
	return &postgresUserRepository{db: db}
}

func (r *postgresUserRepository) SetVerified(ctx context.Context, id uuid.UUID) error {
	query := `UPDATE users SET is_verified = true, verified_at = NOW(), updated_at = NOW() WHERE id = $1`
	_, err := r.db.ExecContext(ctx, query, id)
	return err
}

func (r *postgresUserRepository) Create(ctx context.Context, user *models.User) error {
	query := `
		INSERT INTO users (id, auth_uid, name, email, phn_number, is_verified, created_at, updated_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id
	`
	// Assuming ID is generated by caller or DB (using caller generated UUID here)
	if user.ID == uuid.Nil {
		user.ID = uuid.New()
	}

	_, err := r.db.ExecContext(ctx, query,
		user.ID,
		user.AuthUID,
		user.Name,
		user.Email,
		user.PhnNumber,
		user.IsVerified,
		user.CreatedAt,
		user.UpdatedAt,
	)
	return err
}

func (r *postgresUserRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	user := &models.User{}
	query := `SELECT id, auth_uid, name, email, phn_number, is_verified, created_at, updated_at FROM users WHERE email = $1`
	err := r.db.QueryRowContext(ctx, query, email).Scan(
		&user.ID,
		&user.AuthUID,
		&user.Name,
		&user.Email,
		&user.PhnNumber,
		&user.IsVerified,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil // Or custom ErrNotFound
		}
		return nil, err
	}
	return user, nil
}

func (r *postgresUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	// Implementation similar to GetByEmail
	return nil, nil // Placeholder
}

func (r *postgresUserRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	var exists bool
	query := `SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)`
	err := r.db.QueryRowContext(ctx, query, email).Scan(&exists)
	return exists, err
}
